# Where things are
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'
timezone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

sass:
  style: compressed

# Custom
domain: minddust.com
url: http://www.minddust.com
title: minddust.com
description: Portfolio website of Stephan Gro√ü
copyright: 2013&mdash;2016
name: minddust
author: minddust
twitter:
  username: minddust
github:
  username: minddust
